"""Catalogue officiel des permissions RBAC SIA (V1)."""

from __future__ import annotations

# DASHBOARD
PERMISSION_DASHBOARD_READ = "dashboard.read"

# RECHERCHE
PERMISSION_SEARCH_DOCUMENT = "search.document"
PERMISSION_SEARCH_ADVANCED = "search.advanced"

# DOCUMENTS
PERMISSION_DOCUMENT_READ = "document.read"
PERMISSION_DOCUMENT_CREATE = "document.create"
PERMISSION_DOCUMENT_UPDATE = "document.update"
PERMISSION_DOCUMENT_DELETE = "document.delete"
PERMISSION_DOCUMENT_VALIDATE = "document.validate"
PERMISSION_DOCUMENT_UNVALIDATE = "document.unvalidate"
PERMISSION_DOCUMENT_EXPORT = "document.export"
PERMISSION_DOCUMENT_PRINT = "document.print"
PERMISSION_DOCUMENT_ASSIGN_BUREAU = "document.assign_bureau"

# PIECES JOINTES
PERMISSION_ATTACHMENT_READ = "attachment.read"
PERMISSION_ATTACHMENT_DOWNLOAD = "attachment.download"
PERMISSION_ATTACHMENT_CREATE = "attachment.create"
PERMISSION_ATTACHMENT_UPDATE = "attachment.update"
PERMISSION_ATTACHMENT_DELETE = "attachment.delete"

# CHAMPS METIER
PERMISSION_DOCUMENT_FIELD_READ = "document_field.read"
PERMISSION_DOCUMENT_FIELD_CREATE = "document_field.create"
PERMISSION_DOCUMENT_FIELD_UPDATE = "document_field.update"
PERMISSION_DOCUMENT_FIELD_DELETE = "document_field.delete"

# BUREAUX
PERMISSION_BUREAU_READ = "bureau.read"
PERMISSION_BUREAU_CREATE = "bureau.create"
PERMISSION_BUREAU_UPDATE = "bureau.update"
PERMISSION_BUREAU_DISABLE = "bureau.disable"

# UTILISATEURS
PERMISSION_USER_READ = "user.read"
PERMISSION_USER_CREATE = "user.create"
PERMISSION_USER_UPDATE = "user.update"
PERMISSION_USER_DISABLE = "user.disable"
PERMISSION_USER_ASSIGN_ROLE = "user.assign_role"
PERMISSION_USER_ASSIGN_PERMISSION = "user.assign_permission"
PERMISSION_USER_REVOKE_PERMISSION = "user.revoke_permission"
PERMISSION_USER_GRANT_TEMPORARY_PERMISSION = "user.grant_temporary_permission"
PERMISSION_USER_REVOKE_TEMPORARY_PERMISSION = "user.revoke_temporary_permission"

# ROLES
PERMISSION_ROLE_READ = "role.read"
PERMISSION_ROLE_CREATE = "role.create"
PERMISSION_ROLE_UPDATE = "role.update"
PERMISSION_ROLE_DISABLE = "role.disable"
PERMISSION_ROLE_ASSIGN = "role.assign"
PERMISSION_ROLE_REVOKE = "role.revoke"

# PERMISSIONS
PERMISSION_PERMISSION_READ = "permission.read"
PERMISSION_PERMISSION_ASSIGN = "permission.assign"
PERMISSION_PERMISSION_REVOKE = "permission.revoke"

# AUTORISATIONS
PERMISSION_AUTHORIZATION_REQUEST = "authorization.request"
PERMISSION_AUTHORIZATION_READ = "authorization.read"
PERMISSION_AUTHORIZATION_APPROVE = "authorization.approve"
PERMISSION_AUTHORIZATION_REJECT = "authorization.reject"
PERMISSION_AUTHORIZATION_CANCEL = "authorization.cancel"

# NOTIFICATIONS
PERMISSION_NOTIFICATION_READ = "notification.read"
PERMISSION_NOTIFICATION_MARK_READ = "notification.mark_read"


ALL_PERMISSIONS = (
    # DASHBOARD
    PERMISSION_DASHBOARD_READ,
    # RECHERCHE
    PERMISSION_SEARCH_DOCUMENT,
    PERMISSION_SEARCH_ADVANCED,
    # DOCUMENTS
    PERMISSION_DOCUMENT_READ,
    PERMISSION_DOCUMENT_CREATE,
    PERMISSION_DOCUMENT_UPDATE,
    PERMISSION_DOCUMENT_DELETE,
    PERMISSION_DOCUMENT_VALIDATE,
    PERMISSION_DOCUMENT_UNVALIDATE,
    PERMISSION_DOCUMENT_EXPORT,
    PERMISSION_DOCUMENT_PRINT,
    PERMISSION_DOCUMENT_ASSIGN_BUREAU,
    # PIECES JOINTES
    PERMISSION_ATTACHMENT_READ,
    PERMISSION_ATTACHMENT_DOWNLOAD,
    PERMISSION_ATTACHMENT_CREATE,
    PERMISSION_ATTACHMENT_UPDATE,
    PERMISSION_ATTACHMENT_DELETE,
    # CHAMPS METIER
    PERMISSION_DOCUMENT_FIELD_READ,
    PERMISSION_DOCUMENT_FIELD_CREATE,
    PERMISSION_DOCUMENT_FIELD_UPDATE,
    PERMISSION_DOCUMENT_FIELD_DELETE,
    # BUREAUX
    PERMISSION_BUREAU_READ,
    PERMISSION_BUREAU_CREATE,
    PERMISSION_BUREAU_UPDATE,
    PERMISSION_BUREAU_DISABLE,
    # UTILISATEURS
    PERMISSION_USER_READ,
    PERMISSION_USER_CREATE,
    PERMISSION_USER_UPDATE,
    PERMISSION_USER_DISABLE,
    PERMISSION_USER_ASSIGN_ROLE,
    PERMISSION_USER_ASSIGN_PERMISSION,
    PERMISSION_USER_REVOKE_PERMISSION,
    PERMISSION_USER_GRANT_TEMPORARY_PERMISSION,
    PERMISSION_USER_REVOKE_TEMPORARY_PERMISSION,
    # ROLES
    PERMISSION_ROLE_READ,
    PERMISSION_ROLE_CREATE,
    PERMISSION_ROLE_UPDATE,
    PERMISSION_ROLE_DISABLE,
    PERMISSION_ROLE_ASSIGN,
    PERMISSION_ROLE_REVOKE,
    # PERMISSIONS
    PERMISSION_PERMISSION_READ,
    PERMISSION_PERMISSION_ASSIGN,
    PERMISSION_PERMISSION_REVOKE,
    # AUTORISATIONS
    PERMISSION_AUTHORIZATION_REQUEST,
    PERMISSION_AUTHORIZATION_READ,
    PERMISSION_AUTHORIZATION_APPROVE,
    PERMISSION_AUTHORIZATION_REJECT,
    PERMISSION_AUTHORIZATION_CANCEL,
    # NOTIFICATIONS
    PERMISSION_NOTIFICATION_READ,
    PERMISSION_NOTIFICATION_MARK_READ,
)

ALL_PERMISSIONS_SET = frozenset(ALL_PERMISSIONS)


def is_known_permission(permission: str) -> bool:
    """Retourne True si la permission existe dans le catalogue officiel."""

    return permission in ALL_PERMISSIONS_SET
