"""create_documents_table

Revision ID: 372fce43d5f0
Revises: 
Create Date: 2026-08-08 03:33:10.196795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372fce43d5f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_archive', sa.String(length=100), nullable=False),
    sa.Column('nom_document', sa.String(length=255), nullable=False),
    sa.Column('date_creation', sa.Date(), nullable=False),
    sa.Column('type_document', sa.String(length=100), nullable=False),
    sa.Column('phase_enregistrement', sa.String(length=100), nullable=True),
    sa.Column('code_foncier', sa.String(length=100), nullable=True),
    sa.Column('circo_fonciere', sa.String(length=100), nullable=True),
    sa.Column('numero_ordre', sa.Integer(), nullable=True),
    sa.Column('encodeur', sa.String(length=150), nullable=True),
    sa.Column('remarque', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_archive')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
