"""create_reference_tables

Revision ID: 856dd8b9b901
Revises: 372fce43d5f0
Create Date: 2026-08-08 03:46:34.263278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856dd8b9b901'
down_revision: Union[str, Sequence[str], None] = '372fce43d5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circonscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libelle')
    )
    op.create_index(op.f('ix_document_types_id'), 'document_types', ['id'], unique=False)
    op.create_table('phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libelle')
    )
    op.create_index(op.f('ix_phases_id'), 'phases', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=True),
    sa.Column('prenom', sa.String(length=150), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.add_column('documents', sa.Column('type_document_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('phase_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('circonscription_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('encodeur_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'circonscriptions', ['circonscription_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'users', ['encodeur_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'document_types', ['type_document_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'phases', ['phase_id'], ['id'])
    #op.drop_column('documents', 'type_document')
    #op.drop_column('documents', 'encodeur')
    #op.drop_column('documents', 'phase_enregistrement')
    #op.drop_column('documents', 'circo_fonciere')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('circo_fonciere', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('phase_enregistrement', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('encodeur', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('type_document', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'encodeur_id')
    op.drop_column('documents', 'circonscription_id')
    op.drop_column('documents', 'phase_id')
    op.drop_column('documents', 'type_document_id')
    op.drop_table('users')
    op.drop_index(op.f('ix_phases_id'), table_name='phases')
    op.drop_table('phases')
    op.drop_index(op.f('ix_document_types_id'), table_name='document_types')
    op.drop_table('document_types')
    op.drop_table('circonscriptions')
    # ### end Alembic commands ###
